use dbx_core::connection::AppState;
use dbx_core::database_export::{export_database_sql_core, DatabaseExportRequest, ExportStatus};
use dbx_core::models::connection::{ConnectionConfig, DatabaseType};
use dbx_core::query::execute_sql_statement;
use dbx_core::query_result_export::{export_query_result_core, QueryResultExportRequest};
use dbx_core::sql::SqlFileRequest;
use dbx_core::sql_file_import::execute_sql_file_path;
use dbx_core::table_export::{export_table_data_core, TableExportRequest};
use std::sync::{Arc, Mutex};
use tokio_util::sync::CancellationToken;

fn live_postgres_config(id: &str, database: &str) -> ConnectionConfig {
    let host = std::env::var("DBX_LIVE_POSTGRES_EXPORT_HOST").expect("DBX_LIVE_POSTGRES_EXPORT_HOST");
    let port =
        std::env::var("DBX_LIVE_POSTGRES_EXPORT_PORT").ok().and_then(|value| value.parse::<u16>().ok()).unwrap_or(5432);
    let username = std::env::var("DBX_LIVE_POSTGRES_EXPORT_USER").expect("DBX_LIVE_POSTGRES_EXPORT_USER");
    let password = std::env::var("DBX_LIVE_POSTGRES_EXPORT_PASSWORD").expect("DBX_LIVE_POSTGRES_EXPORT_PASSWORD");

    serde_json::from_value(serde_json::json!({
        "id": id,
        "name": id,
        "db_type": DatabaseType::Postgres,
        "host": host,
        "port": port,
        "username": username,
        "password": password,
        "database": database,
        "ssl": false,
        "connect_timeout_secs": 10,
        "query_timeout_secs": 30,
        "idle_timeout_secs": 60,
        "keepalive_interval_secs": 0
    }))
    .expect("live PostgreSQL export config should deserialize")
}

#[tokio::test]
#[ignore = "requires a live PostgreSQL account with CREATE DATABASE privilege"]
async fn live_postgres_all_schema_export_restores_one_sql_file() {
    let suffix = uuid::Uuid::new_v4().simple().to_string();
    let source_database = format!("dbx_issue8336_src_{}", &suffix[..12]);
    let target_database = format!("dbx_issue8336_dst_{}", &suffix[..12]);
    let expected_export_database = source_database.clone();
    let admin_connection_id = format!("postgres-all-schema-admin-{suffix}");
    let source_connection_id = format!("postgres-all-schema-source-{suffix}");
    let target_connection_id = format!("postgres-all-schema-target-{suffix}");
    let dir = tempfile::tempdir().expect("create export temp directory");
    let storage =
        dbx_core::persistence::test_storage::open(&dir.path().join("storage.db")).await.expect("open temp storage");
    let state = Arc::new(AppState::new_with_plugin_and_agent_dir_and_app_version(
        storage,
        dir.path().join("plugins"),
        dir.path().join("agents"),
        env!("CARGO_PKG_VERSION"),
    ));
    state
        .configs
        .write()
        .await
        .insert(admin_connection_id.clone(), live_postgres_config(&admin_connection_id, "postgres"));
    for database in [&source_database, &target_database] {
        Box::pin(execute_sql_statement(
            &state,
            &admin_connection_id,
            "postgres",
            &format!("CREATE DATABASE \"{database}\""),
            None,
            None,
        ))
        .await
        .expect("create disposable PostgreSQL database");
    }
    state
        .configs
        .write()
        .await
        .insert(source_connection_id.clone(), live_postgres_config(&source_connection_id, &source_database));
    state
        .configs
        .write()
        .await
        .insert(target_connection_id.clone(), live_postgres_config(&target_connection_id, &target_database));

    for statement in [
        "CREATE SCHEMA inventory",
        "CREATE SCHEMA reporting",
        "CREATE TABLE public.accounts (id integer PRIMARY KEY, name text NOT NULL)",
        "CREATE TABLE public.identity_always (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name text NOT NULL)",
        "CREATE TABLE public.identity_default (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL)",
        "CREATE TABLE public.serial_ids (id serial PRIMARY KEY, name text NOT NULL)",
        "CREATE TABLE public.identity_desc (id integer GENERATED ALWAYS AS IDENTITY (START WITH 0 INCREMENT BY -1 MINVALUE -100 MAXVALUE 0) PRIMARY KEY, name text NOT NULL)",
        "CREATE TABLE public.identity_unused (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name text NOT NULL)",
        "CREATE TABLE public.serial_unused (id serial PRIMARY KEY, name text NOT NULL)",
        "CREATE TABLE public.identity_empty (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY)",
        "CREATE TABLE public.identity_cycle (id integer GENERATED ALWAYS AS IDENTITY (MINVALUE 1 MAXVALUE 5 CYCLE) PRIMARY KEY, name text NOT NULL)",
        "CREATE TABLE inventory.products (id integer PRIMARY KEY, sku text NOT NULL)",
        "CREATE TABLE reporting.daily_totals (day date PRIMARY KEY, amount numeric(12,2) NOT NULL)",
        "CREATE VIEW reporting.positive_totals AS SELECT day, amount FROM reporting.daily_totals WHERE amount > 0",
        "INSERT INTO public.accounts VALUES (1, 'Alice'), (2, 'Bob')",
        "INSERT INTO inventory.products VALUES (10, 'SKU-10')",
        "INSERT INTO reporting.daily_totals VALUES ('2026-09-07', 42.50)",
        "INSERT INTO public.identity_always (name) VALUES ('one'), ('two')",
        "INSERT INTO public.identity_default (name) VALUES ('one'), ('two')",
        "INSERT INTO public.serial_ids (name) VALUES ('one'), ('two')",
        "INSERT INTO public.identity_always OVERRIDING SYSTEM VALUE VALUES (42, 'explicit')",
        "INSERT INTO public.identity_default VALUES (42, 'explicit')",
        "INSERT INTO public.serial_ids VALUES (42, 'explicit')",
        "ALTER SEQUENCE public.identity_always_id_seq RENAME TO renamed_identity_sequence",
        "ALTER SEQUENCE public.renamed_identity_sequence MINVALUE -100 MAXVALUE 1000 CACHE 3 CYCLE",
        "ALTER SEQUENCE public.serial_ids_id_seq START WITH 10 INCREMENT BY 5 MINVALUE 1 MAXVALUE 1000 CACHE 3 CYCLE",
        "SELECT setval('public.renamed_identity_sequence', 80)",
        "SELECT setval('public.identity_default_id_seq', 80)",
        "SELECT setval('public.serial_ids_id_seq', 80)",
        "INSERT INTO public.identity_desc (name) VALUES ('zero'), ('minus one')",
        "INSERT INTO public.identity_desc OVERRIDING SYSTEM VALUE VALUES (-42, 'explicit')",
        "SELECT setval('public.identity_desc_id_seq', -80)",
        "INSERT INTO public.identity_unused OVERRIDING SYSTEM VALUE VALUES (1, 'explicit')",
        "INSERT INTO public.serial_unused VALUES (1, 'explicit')",
        "INSERT INTO public.identity_cycle (name) VALUES ('one')",
        "INSERT INTO public.identity_cycle OVERRIDING SYSTEM VALUE VALUES (5, 'explicit')",
        "SELECT setval('public.identity_cycle_id_seq', 5)",
        "SELECT nextval('public.identity_cycle_id_seq')",
    ] {
        Box::pin(execute_sql_statement(&state, &source_connection_id, &source_database, statement, None, None))
            .await
            .expect("create source fixture");
    }

    let export_path = dir.path().join("postgres-all-schemas.sql");
    let progress = Arc::new(Mutex::new(Vec::new()));
    let progress_sink = progress.clone();
    export_database_sql_core(
        &state,
        &DatabaseExportRequest {
            export_id: format!("postgres-all-schema-export-{suffix}"),
            connection_id: source_connection_id.clone(),
            database: source_database.clone(),
            schema: String::new(),
            file_path: export_path.display().to_string(),
            selected_tables: Vec::new(),
            excluded_tables: Vec::new(),
            include_structure: true,
            include_data: true,
            include_objects: true,
            include_create_database: false,
            drop_table_if_exists: false,
            omit_auto_increment: false,
            preserve_original_language: false,
            fail_on_error: true,
            prevent_overwrite: false,
            output_compression: Default::default(),
            insert_dialect: Default::default(),
            insert_mode: Default::default(),
            snapshot_session_id: None,
            batch_size: 1000,
            split_max_mb: None,
        },
        move |event| progress_sink.lock().expect("progress mutex poisoned").push(event),
    )
    .await
    .expect("export every PostgreSQL schema");

    let exported = std::fs::read_to_string(&export_path).expect("read combined export");
    for expected in [
        "CREATE SCHEMA IF NOT EXISTS \"public\";",
        "CREATE SCHEMA IF NOT EXISTS \"inventory\";",
        "CREATE SCHEMA IF NOT EXISTS \"reporting\";",
        "CREATE TABLE \"public\".\"accounts\"",
        "CREATE TABLE \"inventory\".\"products\"",
        "CREATE TABLE \"reporting\".\"daily_totals\"",
        "positive_totals",
    ] {
        assert!(exported.contains(expected), "missing {expected} in combined export:\n{exported}");
    }
    assert_eq!(exported.matches("-- Schema export:").count(), 3, "unexpected schema sections:\n{exported}");
    assert!(
        progress.lock().expect("progress mutex poisoned").iter().any(|event| {
            matches!(event.status, ExportStatus::Done) && event.current_object == expected_export_database
        }),
        "combined export must emit a terminal Done event"
    );

    execute_sql_file_path(
        &state,
        &SqlFileRequest {
            txn_session_id: None,
            execution_id: format!("postgres-all-schema-import-{suffix}"),
            connection_id: target_connection_id.clone(),
            database: target_database.clone(),
            schema: None,
            file_path: export_path.display().to_string(),
            continue_on_error: false,
            selected_tables: None,
            part_cooldown_ms: 0,
            skip_relational_constraints: false,
        },
        &export_path,
        CancellationToken::new(),
        std::time::Instant::now(),
        |_| {},
    )
    .await
    .expect("restore combined PostgreSQL export");

    let restored = Box::pin(execute_sql_statement(
        &state,
        &target_connection_id,
        &target_database,
        "SELECT
           (SELECT count(*) FROM public.accounts),
           (SELECT count(*) FROM inventory.products),
           (SELECT amount::text FROM reporting.positive_totals WHERE day = DATE '2026-09-07')",
        None,
        None,
    ))
    .await
    .expect("query restored schemas");
    assert_eq!(restored.rows, vec![vec![serde_json::json!(2), serde_json::json!(1), serde_json::json!("42.50")]]);

    for (table, next_id, increment, duplicate_id) in [
        ("identity_always", 81, 1, 42),
        ("identity_default", 81, 1, 42),
        ("serial_ids", 85, 5, 42),
        ("identity_desc", -81, -1, -42),
        ("identity_unused", 2, 1, 1),
        ("serial_unused", 2, 1, 1),
        ("identity_cycle", 2, 1, 5),
    ] {
        let select = format!("SELECT id, name FROM public.{table} ORDER BY id");
        let expected =
            Box::pin(execute_sql_statement(&state, &source_connection_id, &source_database, &select, None, None))
                .await
                .unwrap()
                .rows;
        let restored =
            Box::pin(execute_sql_statement(&state, &target_connection_id, &target_database, &select, None, None))
                .await
                .unwrap();
        assert_eq!(restored.rows, expected, "database export must preserve {table} IDs");
        let parameters_sql = format!(
            "SELECT seqstart, seqmin, seqmax, seqincrement, seqcache, seqcycle FROM pg_sequence \
             WHERE seqrelid = pg_get_serial_sequence('public.{table}', 'id')::regclass"
        );
        let source_parameters = Box::pin(execute_sql_statement(
            &state,
            &source_connection_id,
            &source_database,
            &parameters_sql,
            None,
            None,
        ))
        .await
        .unwrap();
        let target_parameters = Box::pin(execute_sql_statement(
            &state,
            &target_connection_id,
            &target_database,
            &parameters_sql,
            None,
            None,
        ))
        .await
        .unwrap();
        assert_eq!(target_parameters.rows, source_parameters.rows, "restore {table} sequence parameters");
        let next = Box::pin(execute_sql_statement(
            &state,
            &target_connection_id,
            &target_database,
            &format!("INSERT INTO public.{table} (name) VALUES ('next') RETURNING id"),
            None,
            None,
        ))
        .await
        .unwrap();
        assert_eq!(next.rows, vec![vec![serde_json::json!(next_id)]], "restore {table} sequence state");
        let sequence_state_sql =
            format!("SELECT pg_sequence_last_value(pg_get_serial_sequence('public.{table}', 'id')::regclass)::text");
        let before_data_import = Box::pin(execute_sql_statement(
            &state,
            &target_connection_id,
            &target_database,
            &sequence_state_sql,
            None,
            None,
        ))
        .await
        .unwrap();

        let columns =
            dbx_core::schema::get_columns_core(&state, &source_connection_id, &source_database, "public", table)
                .await
                .unwrap();
        for mode in ["single", "batch"] {
            for entry in ["table", "query"] {
                let path = dir.path().join(format!("{table}-{mode}-{entry}.sql"));
                if entry == "table" {
                    // No supplied columns: exercise the table exporter's metadata query.
                    let request: TableExportRequest = serde_json::from_value(serde_json::json!({
                        "exportId": format!("{suffix}-{table}-{mode}-{entry}"),
                        "connectionId": source_connection_id, "database": source_database,
                        "schema": "public", "tableName": table, "filePath": path,
                        "format": "sql", "insertMode": mode, "batchSize": 2
                    }))
                    .unwrap();
                    export_table_data_core(&state, &request, |_| {}).await.unwrap();
                } else {
                    // Query export receives extras from the result's table metadata.
                    let request: QueryResultExportRequest = serde_json::from_value(serde_json::json!({
                        "exportId": format!("{suffix}-{table}-{mode}-{entry}"),
                        "connectionId": source_connection_id, "database": source_database,
                        "schema": "public", "databaseType": "postgres", "sql": select,
                        "queryBaseSql": select, "exportTableName": table, "filePath": path,
                        "format": "sql", "insertMode": mode, "pageSize": 2,
                        "exportColumnExtras": columns.iter().map(|c| c.extra.clone()).collect::<Vec<_>>()
                    }))
                    .unwrap();
                    export_query_result_core(&state, &request, None, |_| {}).await.unwrap();
                }
                Box::pin(execute_sql_statement(
                    &state,
                    &target_connection_id,
                    &target_database,
                    &format!("TRUNCATE public.{table} CONTINUE IDENTITY"),
                    None,
                    None,
                ))
                .await
                .unwrap();
                execute_sql_file_path(
                    &state,
                    &SqlFileRequest {
                        txn_session_id: None,
                        execution_id: uuid::Uuid::new_v4().to_string(),
                        connection_id: target_connection_id.clone(),
                        database: target_database.clone(),
                        schema: None,
                        file_path: path.display().to_string(),
                        continue_on_error: false,
                        selected_tables: None,
                        part_cooldown_ms: 0,
                        skip_relational_constraints: false,
                    },
                    &path,
                    CancellationToken::new(),
                    std::time::Instant::now(),
                    |_| {},
                )
                .await
                .unwrap();
                let restored = Box::pin(execute_sql_statement(
                    &state,
                    &target_connection_id,
                    &target_database,
                    &select,
                    None,
                    None,
                ))
                .await
                .unwrap();
                assert_eq!(restored.rows, expected, "{entry}/{mode} must preserve {table} IDs");
            }
        }
        // Data-only exports preserve values, but deliberately leave the target sequence alone.
        let after_data_import = Box::pin(execute_sql_statement(
            &state,
            &target_connection_id,
            &target_database,
            &sequence_state_sql,
            None,
            None,
        ))
        .await
        .unwrap();
        assert_eq!(after_data_import.rows, before_data_import.rows, "data import must not reset {table} sequence");
        let next = Box::pin(execute_sql_statement(
            &state,
            &target_connection_id,
            &target_database,
            &format!("INSERT INTO public.{table} (name) VALUES ('after data import') RETURNING id"),
            None,
            None,
        ))
        .await
        .unwrap();
        let after_id = next.rows[0][0].as_i64().unwrap();
        assert!(
            (after_id - next_id) * increment > 0 && (after_id - next_id) % increment == 0,
            "{table} must continue in the configured direction/step: {after_id}"
        );
        assert!(
            Box::pin(execute_sql_statement(
                &state,
                &target_connection_id,
                &target_database,
                &format!("INSERT INTO public.{table} OVERRIDING SYSTEM VALUE VALUES ({duplicate_id}, 'duplicate')"),
                None,
                None,
            ))
            .await
            .is_err(),
            "primary key remains enforced for {table}"
        );
    }
    let empty_next = Box::pin(execute_sql_statement(
        &state,
        &target_connection_id,
        &target_database,
        "INSERT INTO public.identity_empty DEFAULT VALUES RETURNING id",
        None,
        None,
    ))
    .await
    .unwrap();
    assert_eq!(
        empty_next.rows,
        vec![vec![serde_json::json!(1)]],
        "an empty uncalled sequence must retain its first value"
    );
    assert!(
        Box::pin(execute_sql_statement(
            &state,
            &target_connection_id,
            &target_database,
            "INSERT INTO public.identity_always VALUES (99, 'forbidden')",
            None,
            None,
        ))
        .await
        .is_err(),
        "ALWAYS identity remains enforced after restore"
    );

    for database in [&source_database, &target_database] {
        Box::pin(execute_sql_statement(
            &state,
            &admin_connection_id,
            "postgres",
            &format!("DROP DATABASE \"{database}\" WITH (FORCE)"),
            None,
            None,
        ))
        .await
        .expect("drop disposable PostgreSQL database");
    }
}
