#![recursion_limit = "256"]

pub mod admin;
pub mod ai;
pub mod data;
pub mod host;
pub mod persistence;
pub mod safety;

pub use dbx_ai_provider::{
    agent_events, ai_claude_code_cli, ai_cli_agent, ai_codebuddy_cli, ai_codex_cli, ai_cursor_cli, ai_effort,
    ai_grok_cli, ai_opencode_cli, ai_pi_agent_cli, ai_qoder_cli, token_usage,
};
pub use dbx_platform::{path_utils, process};

pub use ai::agent_explain;
pub use ai::agent_kv;
pub use ai::agent_loop;
pub use ai::agent_tools;
pub use ai::plugin_tools;
pub use ai::skill_tools;
pub use ai::tool_approval;
pub use dbx_drivers::agent_catalog;
pub use dbx_drivers::agent_connection;
pub use dbx_drivers::agent_manager;
pub use dbx_drivers::agent_offline_export;
pub use dbx_drivers::agent_recovery;
pub use dbx_drivers::agent_runtime;
pub use dbx_drivers::agent_service;
pub use dbx_drivers::backend_error;
pub use dbx_drivers::oracle_oci;
pub use host::changelog;
pub use persistence::cloud_sync;
pub use persistence::config;
pub mod connection;
pub use admin::consul;
pub use connection::connection_secrets;
pub use data::correction;
pub use data::csv_export;
pub use data::data_compare;
pub use data::database_export;
pub use dbx_drivers::database_capabilities;
pub use dbx_sql::data_grid_extractors;
pub use dbx_sql::data_grid_sql;
pub use dbx_sql::database_search_sql;
pub use dbx_types::database_manifest;
pub mod db;
#[cfg(feature = "mq-admin")]
pub use admin::mq;
#[cfg(feature = "mq-admin")]
pub use admin::mqtt;
pub use admin::nacos;
pub use ai::mcp_policy;
pub use ai::prompt_template;
pub use connection::driver_runtime;
pub use connection::jdbc;
pub use data::docs;
pub use data::export_runtime;
pub use data::mongodb_dump;
pub use data::mongodb_import_export;
pub use dbx_drivers::mongo_oidc;
pub use dbx_drivers::mongo_shell;
pub use dbx_drivers::salesforce_oauth;
pub use dbx_formats::export_split_zip;
pub use dbx_plugin_runtime::plugins;
pub use dbx_sql::db_admin_sql;
pub use dbx_sql::dml_binding;
pub use dbx_sql::dml_preview_sql;
pub(crate) use dbx_sql::mysql_ddl_normalize;
pub use dbx_sql::mysql_event_sql;
pub use dbx_sql::object_source_sql;
pub use dbx_types::models;
pub use host::external;
pub use persistence::history;
pub use query::document_ops;
pub use query::hbase_ops;
pub use query::mongo_ops;
pub use query::object_cache;
pub use safety::production_safety;
pub mod query;
pub use connection::runtime_config;
pub use data::query_result_export;
pub use dbx_sql::query_execution_sql;
pub use dbx_sql::query_result_sql;
pub use persistence::saved_sql;
pub use query::query_cancel;
pub use query::redis_ops;
pub use safety::risk_metrics;
pub mod scheduled_backup;
pub mod schema;
pub mod skills;
pub use connection::session_credentials;
pub use connection::task_supervisor;
pub use data::script_generator;
pub use data::sql_file_import;
pub use data::sqlite_backup;
pub use data::table_export;
pub use data::table_import;
pub use data::transfer;
pub use data::transfer_rebuild;
pub use dbx_drivers::ssh_config;
pub use dbx_formats::sql_file_zip_package;
pub use dbx_formats::temporal_format;
pub use dbx_formats::text_export;
pub use dbx_formats::xlsx_export;
pub use dbx_sql::schema_diff;
pub use dbx_sql::sql;
pub use dbx_sql::sql_analysis;
pub use dbx_sql::sql_diagnostics;
pub use dbx_sql::sql_dialect;
pub use dbx_sql::sql_editability;
pub use dbx_sql::sql_error_position;
pub use dbx_sql::sql_parser;
pub use dbx_sql::sql_risk;
pub(crate) use dbx_sql::sqlserver_temporal;
pub use dbx_types::types;
pub use host::update;
pub use persistence::state_persistence;
pub use persistence::storage;
pub use query::two_phase_commit;
pub use safety::write_unlock;
pub use schema::table_structure_sql;

pub use dbx_platform::download::{
    download_candidate_urls, race_download, race_download_urls, DownloadSource, CNB_RELEASE_DOWNLOAD_PREFIX,
    GITHUB_RELEASE_DOWNLOAD_PREFIX, R2_CDN_BASE,
};
