/**
 * Hive / Spark SQL 家族内置函数签名。
 *
 * 说明：
 * - 适用于 Hive、Spark、Databricks、Impala、Transwarp Inceptor、Kyuubi、Argo 等 Hive SQL 兼容引擎。
 * - 只收录高频 SQL 内置函数，参数名按 Hive/Spark 官方文档口径，仅作为补全提示与签名提示，不做语法校验。
 * - 窗口函数（ROW_NUMBER/RANK/LAG 等）由 `WINDOW_FUNCTIONS` 单独提供，此处不重复。
 */
export const HIVE_SPARK_FUNCTION_SIGNATURES = new Map<string, string[]>([
  // 空值 / 条件
  ["NVL", ["expr", "replacement"]],
  ["NVL2", ["expr", "if_not_null", "if_null"]],
  ["IF", ["condition", "true_value", "false_value"]],
  ["ISNULL", ["expr"]],
  ["ISNOTNULL", ["expr"]],
  ["COALESCE", ["...values"]],
  ["NULLIF", ["value1", "value2"]],
  ["GREATEST", ["...values"]],
  ["LEAST", ["...values"]],
  ["ZEROIFNULL", ["expr"]],
  ["NULLIFZERO", ["expr"]],
  ["ASSERT_TRUE", ["condition"]],
  // 字符串
  ["CONCAT", ["...values"]],
  ["CONCAT_WS", ["separator", "...values"]],
  ["SUBSTR", ["str", "pos", "len"]],
  ["SUBSTRING", ["str", "pos", "len"]],
  ["LENGTH", ["str"]],
  ["UPPER", ["str"]],
  ["LOWER", ["str"]],
  ["INITCAP", ["str"]],
  ["TRIM", ["str"]],
  ["LTRIM", ["trim_str", "str"]],
  ["RTRIM", ["trim_str", "str"]],
  ["LPAD", ["str", "len", "pad"]],
  ["RPAD", ["str", "len", "pad"]],
  ["REPEAT", ["str", "n"]],
  ["REVERSE", ["str"]],
  ["SPLIT", ["str", "pattern"]],
  ["INSTR", ["str", "substr"]],
  ["LOCATE", ["substr", "str", "pos"]],
  ["REGEXP_EXTRACT", ["str", "pattern", "idx"]],
  ["REGEXP_EXTRACT_ALL", ["str", "pattern"]],
  ["REGEXP_REPLACE", ["str", "pattern", "replacement"]],
  ["ASCII", ["str"]],
  ["CHR", ["num"]],
  ["SOUNDEX", ["str"]],
  ["TRANSLATE", ["input", "from", "to"]],
  ["BASE64", ["bin"]],
  ["UNBASE64", ["str"]],
  ["HEX", ["expr"]],
  ["UNHEX", ["expr"]],
  ["MD5", ["expr"]],
  ["SHA2", ["expr", "bit_length"]],
  ["CRC32", ["expr"]],
  ["HASH", ["...values"]],
  // 日期时间（CURRENT_DATE / CURRENT_TIMESTAMP 是关键字项，这里不重复）
  ["NOW", []],
  ["UNIX_TIMESTAMP", []],
  ["TO_UNIX_TIMESTAMP", ["date", "pattern"]],
  ["FROM_UNIXTIME", ["unixtime", "format"]],
  ["DATE_FORMAT", ["date", "format"]],
  ["DATE_ADD", ["start_date", "days"]],
  ["DATE_SUB", ["start_date", "days"]],
  ["DATEDIFF", ["enddate", "startdate"]],
  ["DATE_TRUNC", ["format", "timestamp"]],
  ["TRUNC", ["date", "format"]],
  ["MONTHS_BETWEEN", ["date1", "date2"]],
  ["ADD_MONTHS", ["date", "months"]],
  ["LAST_DAY", ["date"]],
  ["NEXT_DAY", ["date", "day_of_week"]],
  ["TO_DATE", ["date", "format"]],
  ["YEAR", ["date"]],
  ["QUARTER", ["date"]],
  ["MONTH", ["date"]],
  ["DAY", ["date"]],
  ["HOUR", ["date"]],
  ["MINUTE", ["date"]],
  ["SECOND", ["date"]],
  ["WEEKOFYEAR", ["date"]],
  ["DAYOFWEEK", ["date"]],
  ["DAYOFMONTH", ["date"]],
  ["DAYOFYEAR", ["date"]],
  ["FROM_UTC_TIMESTAMP", ["ts", "tz"]],
  ["TO_UTC_TIMESTAMP", ["ts", "tz"]],
  // 集合 / JSON
  ["GET_JSON_OBJECT", ["json", "path"]],
  ["FROM_JSON", ["json", "schema"]],
  ["TO_JSON", ["obj"]],
  ["JSON_TUPLE", ["json", "...paths"]],
  ["EXPLODE", ["array"]],
  ["POSEXPLODE", ["array"]],
  ["INLINE", ["array_of_struct"]],
  ["SIZE", ["array"]],
  ["ARRAY", ["...values"]],
  ["SORT_ARRAY", ["array", "ascending"]],
  ["ARRAY_CONTAINS", ["array", "value"]],
  ["MAP", ["...key_value_pairs"]],
  ["MAP_KEYS", ["map"]],
  ["MAP_VALUES", ["map"]],
  ["STRUCT", ["...values"]],
  ["NAMED_STRUCT", ["name", "...name_value_pairs"]],
  // 聚合 / 分析
  ["COLLECT_LIST", ["expr"]],
  ["COLLECT_SET", ["expr"]],
  ["PERCENTILE", ["expr", "percentage"]],
  ["PERCENTILE_APPROX", ["expr", "percentage"]],
  ["APPROX_COUNT_DISTINCT", ["expr"]],
  ["HISTOGRAM_NUMERIC", ["expr", "bins"]],
  ["STDDEV", ["expr"]],
  ["VARIANCE", ["expr"]],
  ["CORR", ["expr1", "expr2"]],
  ["COVAR_POP", ["expr1", "expr2"]],
  ["COVAR_SAMP", ["expr1", "expr2"]],
  // 数学
  ["ABS", ["expr"]],
  ["CEIL", ["expr"]],
  ["FLOOR", ["expr"]],
  ["ROUND", ["expr", "d"]],
  ["POWER", ["a", "b"]],
  ["SQRT", ["expr"]],
  ["EXP", ["expr"]],
  ["LN", ["expr"]],
  ["LOG", ["base", "expr"]],
  ["LOG10", ["expr"]],
  ["LOG2", ["expr"]],
  ["SIGN", ["expr"]],
  ["PMOD", ["a", "b"]],
  ["FACTORIAL", ["n"]],
  ["BIN", ["expr"]],
  ["CONV", ["num", "from_base", "to_base"]],
  // 高阶函数
  ["TRANSFORM", ["array", "func"]],
  ["FILTER", ["array", "func"]],
  ["EXISTS", ["array", "func"]],
  ["AGGREGATE", ["array", "start", "merge", "finish"]],
]);

/** Hive/Spark 中参数语法特殊的函数，补全时按模板插入 */
export const HIVE_SPARK_FUNCTION_APPLY_TEMPLATES = new Map<string, string>([["EXTRACT", "EXTRACT(${field} FROM ${source})"]]);
