/**
 * PostgreSQL 家族内置函数签名。
 *
 * 说明：
 * - 这里同时作为 PG 兼容库（openGauss / GaussDB / Kingbase / Vastbase / HighGo / UXDB / SunDB / Redshift）
 *   的共享函数表，`sqlCompletion.ts` 里按家族注册。
 * - 只收录高频 SQL 内置函数，参数名按 PostgreSQL 官方文档口径，仅作为补全提示与签名提示，不做语法校验。
 * - 窗口函数（ROW_NUMBER/RANK/LAG 等）由 `WINDOW_FUNCTIONS` 单独提供，此处不重复。
 */
export const POSTGRES_FUNCTION_SIGNATURES = new Map<string, string[]>([
  // 字符串
  ["LENGTH", ["string"]],
  ["CHAR_LENGTH", ["string"]],
  ["OCTET_LENGTH", ["string"]],
  ["UPPER", ["string"]],
  ["LOWER", ["string"]],
  ["INITCAP", ["string"]],
  ["CONCAT", ["...values"]],
  ["CONCAT_WS", ["separator", "...values"]],
  ["LEFT", ["string", "n"]],
  ["RIGHT", ["string", "n"]],
  ["LPAD", ["string", "length", "fill"]],
  ["RPAD", ["string", "length", "fill"]],
  ["TRIM", ["string"]],
  ["BTRIM", ["string", "characters"]],
  ["LTRIM", ["string"]],
  ["RTRIM", ["string"]],
  ["REPLACE", ["string", "from", "to"]],
  ["REPEAT", ["string", "number"]],
  ["SPLIT_PART", ["string", "delimiter", "n"]],
  ["STRPOS", ["string", "substring"]],
  ["POSITION", ["substring IN string"]],
  ["SUBSTRING", ["string FROM start FOR count"]],
  ["OVERLAY", ["string PLACING new FROM start FOR count"]],
  ["FORMAT", ["format", "...values"]],
  ["TRANSLATE", ["string", "from", "to"]],
  ["ASCII", ["string"]],
  ["CHR", ["code"]],
  ["MD5", ["string"]],
  ["ENCODE", ["data", "format"]],
  ["DECODE", ["string", "format"]],
  ["QUOTE_IDENT", ["string"]],
  ["QUOTE_LITERAL", ["string"]],
  // 正则
  ["REGEXP_REPLACE", ["string", "pattern", "replacement", "flags"]],
  ["REGEXP_MATCHES", ["string", "pattern", "flags"]],
  ["REGEXP_MATCH", ["string", "pattern", "flags"]],
  ["REGEXP_SPLIT_TO_ARRAY", ["string", "pattern", "flags"]],
  ["REGEXP_SPLIT_TO_TABLE", ["string", "pattern", "flags"]],
  // 类型转换
  ["TO_CHAR", ["value", "format"]],
  ["TO_DATE", ["text", "format"]],
  ["TO_TIMESTAMP", ["text", "format"]],
  ["TO_NUMBER", ["text", "format"]],
  ["CAST", ["expression AS type"]],
  // 日期时间（CURRENT_DATE / CURRENT_TIME / CURRENT_TIMESTAMP / LOCALTIME / LOCALTIMESTAMP 是关键字项，这里不重复）
  ["NOW", []],
  ["CLOCK_TIMESTAMP", []],
  ["STATEMENT_TIMESTAMP", []],
  ["TRANSACTION_TIMESTAMP", []],
  ["DATE_TRUNC", ["field", "source"]],
  ["DATE_PART", ["field", "source"]],
  ["EXTRACT", ["field FROM source"]],
  ["AGE", ["timestamp", "timestamp"]],
  ["MAKE_DATE", ["year", "month", "day"]],
  ["MAKE_TIME", ["hour", "min", "sec"]],
  ["MAKE_TIMESTAMP", ["year", "month", "day", "hour", "min", "sec"]],
  ["JUSTIFY_DAYS", ["interval"]],
  ["JUSTIFY_HOURS", ["interval"]],
  ["JUSTIFY_INTERVAL", ["interval"]],
  ["PG_SLEEP", ["seconds"]],
  // 数字
  ["ABS", ["number"]],
  ["CEIL", ["number"]],
  ["CEILING", ["number"]],
  ["FLOOR", ["number"]],
  ["ROUND", ["numeric", "int"]],
  ["TRUNC", ["numeric", "int"]],
  ["MOD", ["y", "x"]],
  ["POWER", ["a", "b"]],
  ["SQRT", ["number"]],
  ["EXP", ["number"]],
  ["LN", ["number"]],
  ["LOG", ["b", "x"]],
  ["LOG10", ["number"]],
  ["SIGN", ["number"]],
  ["RANDOM", []],
  ["PI", []],
  ["DEGREES", ["radians"]],
  ["RADIANS", ["degrees"]],
  ["WIDTH_BUCKET", ["operand", "low", "high", "count"]],
  ["GCD", ["a", "b"]],
  ["LCM", ["a", "b"]],
  // 聚合
  ["ARRAY_AGG", ["expression"]],
  ["STRING_AGG", ["expression", "delimiter"]],
  ["JSON_AGG", ["expression"]],
  ["JSONB_AGG", ["expression"]],
  ["JSONB_OBJECT_AGG", ["key", "value"]],
  ["BOOL_AND", ["expression"]],
  ["BOOL_OR", ["expression"]],
  ["EVERY", ["expression"]],
  ["PERCENTILE_CONT", ["fraction"]],
  ["PERCENTILE_DISC", ["fraction"]],
  ["STDDEV", ["expression"]],
  ["VARIANCE", ["expression"]],
  ["CORR", ["y", "x"]],
  ["COVAR_POP", ["y", "x"]],
  ["COVAR_SAMP", ["y", "x"]],
  // 数组 / JSON
  ["UNNEST", ["array"]],
  ["ARRAY_LENGTH", ["array", "dimension"]],
  ["CARDINALITY", ["array"]],
  ["ARRAY_POSITION", ["array", "element"]],
  ["ARRAY_APPEND", ["array", "element"]],
  ["ARRAY_REMOVE", ["array", "element"]],
  ["ARRAY_CAT", ["array1", "array2"]],
  ["ARRAY_TO_STRING", ["array", "delimiter"]],
  ["STRING_TO_ARRAY", ["string", "delimiter"]],
  ["GENERATE_SERIES", ["start", "stop", "step"]],
  ["TO_JSON", ["value"]],
  ["TO_JSONB", ["value"]],
  ["JSONB_BUILD_OBJECT", ["key", "value", "...pairs"]],
  ["JSON_BUILD_OBJECT", ["...key_value_pairs"]],
  ["JSONB_SET", ["target", "path", "new_value"]],
  ["JSONB_EXTRACT_PATH_TEXT", ["jsonb", "...path_elements"]],
  ["JSONB_ARRAY_ELEMENTS", ["jsonb"]],
  ["JSONB_ARRAY_ELEMENTS_TEXT", ["jsonb"]],
  ["JSONB_EACH", ["jsonb"]],
  ["JSONB_OBJECT_KEYS", ["jsonb"]],
  // 系统信息
  ["GEN_RANDOM_UUID", []],
  ["CURRENT_USER", []],
  ["SESSION_USER", []],
  ["CURRENT_SCHEMA", []],
  ["CURRENT_DATABASE", []],
  ["PG_BACKEND_PID", []],
  ["PG_TYPEOF", ["any"]],
]);

/**
 * PostgreSQL 家族中语法与「逗号分隔参数」不同的函数，补全时按模板插入，
 * 例如 `EXTRACT(YEAR FROM created_at)`、`PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary)`。
 * DuckDB 复用 PG 风格语法，也使用这组模板。
 */
export const POSTGRES_FUNCTION_APPLY_TEMPLATES = new Map<string, string>([
  ["EXTRACT", "EXTRACT(${field} FROM ${source})"],
  ["POSITION", "POSITION(${substring} IN ${string})"],
  ["SUBSTRING", "SUBSTRING(${string} FROM ${start} FOR ${count})"],
  ["OVERLAY", "OVERLAY(${string} PLACING ${new} FROM ${start} FOR ${count})"],
  ["PERCENTILE_CONT", "PERCENTILE_CONT(${fraction}) WITHIN GROUP (ORDER BY ${expression})"],
  ["PERCENTILE_DISC", "PERCENTILE_DISC(${fraction}) WITHIN GROUP (ORDER BY ${expression})"],
]);
