/**
 * Trino / PrestoSQL 内置函数签名。
 *
 * 说明：只收录高频 SQL 内置函数，参数名按 Trino 官方文档口径，仅作为补全提示与签名提示，不做语法校验。
 * 窗口函数（ROW_NUMBER/RANK/LAG 等）由 `WINDOW_FUNCTIONS` 单独提供，此处不重复。
 */
export const TRINO_FUNCTION_SIGNATURES = new Map<string, string[]>([
  // 字符串
  ["CHR", ["n"]],
  ["CODEPOINT", ["string"]],
  ["CONCAT", ["...strings"]],
  ["LENGTH", ["string"]],
  ["UPPER", ["string"]],
  ["LOWER", ["string"]],
  ["LPAD", ["string", "size", "padstring"]],
  ["RPAD", ["string", "size", "padstring"]],
  ["LTRIM", ["string"]],
  ["RTRIM", ["string"]],
  ["TRIM", ["string"]],
  ["REPLACE", ["string", "search", "replacement"]],
  ["REVERSE", ["string"]],
  ["SPLIT", ["string", "delimiter"]],
  ["SPLIT_PART", ["string", "delimiter", "index"]],
  ["STRPOS", ["string", "substring"]],
  ["POSITION", ["substring IN string"]],
  ["SUBSTR", ["string", "start", "length"]],
  ["SUBSTRING", ["string FROM start FOR length"]],
  ["LEVENSHTEIN_DISTANCE", ["string1", "string2"]],
  ["HAMMING_DISTANCE", ["string1", "string2"]],
  ["NORMALIZE", ["string", "form"]],
  ["FORMAT", ["format", "...args"]],
  ["REGEXP_EXTRACT", ["string", "pattern", "group"]],
  ["REGEXP_EXTRACT_ALL", ["string", "pattern"]],
  ["REGEXP_LIKE", ["string", "pattern"]],
  ["REGEXP_REPLACE", ["string", "pattern", "replacement"]],
  ["REGEXP_SPLIT", ["string", "pattern"]],
  // 日期时间（CURRENT_* / LOCALTIME / LOCALTIMESTAMP 是关键字项，这里不重复）
  ["NOW", []],
  ["DATE", ["x"]],
  ["DATE_ADD", ["unit", "value", "timestamp"]],
  ["DATE_DIFF", ["unit", "timestamp1", "timestamp2"]],
  ["DATE_FORMAT", ["timestamp", "format"]],
  ["DATE_PARSE", ["string", "format"]],
  ["DATE_TRUNC", ["unit", "x"]],
  ["FORMAT_DATETIME", ["timestamp", "format"]],
  ["PARSE_DATETIME", ["string", "format"]],
  ["FROM_UNIXTIME", ["unixtime"]],
  ["TO_UNIXTIME", ["timestamp"]],
  ["TO_ISO8601", ["timestamp"]],
  ["AT_TIMEZONE", ["timestamp", "zone"]],
  ["WITH_TIMEZONE", ["timestamp", "zone"]],
  ["EXTRACT", ["field FROM source"]],
  // 数学
  ["ABS", ["x"]],
  ["CEIL", ["x"]],
  ["CEILING", ["x"]],
  ["FLOOR", ["x"]],
  ["ROUND", ["x", "d"]],
  ["TRUNCATE", ["x", "d"]],
  ["MOD", ["n", "m"]],
  ["POWER", ["x", "p"]],
  ["SQRT", ["x"]],
  ["EXP", ["x"]],
  ["LN", ["x"]],
  ["LOG", ["b", "x"]],
  ["LOG2", ["x"]],
  ["LOG10", ["x"]],
  ["SIGN", ["x"]],
  ["RANDOM", ["n"]],
  ["PI", []],
  ["E", []],
  ["DEGREES", ["x"]],
  ["RADIANS", ["x"]],
  // 数组 / Map
  ["ARRAY_AGG", ["x"]],
  ["ARRAY_DISTINCT", ["array"]],
  ["ARRAY_JOIN", ["array", "delimiter"]],
  ["CARDINALITY", ["array"]],
  ["CONTAINS", ["array", "element"]],
  ["ELEMENT_AT", ["array", "index"]],
  ["FLATTEN", ["array"]],
  ["FILTER", ["array", "lambda"]],
  ["TRANSFORM", ["array", "lambda"]],
  ["REDUCE", ["array", "initial", "lambda", "lambda"]],
  ["SLICE", ["array", "start", "length"]],
  ["SEQUENCE", ["start", "stop", "step"]],
  ["ZIP", ["array1", "array2"]],
  ["ZIP_WITH", ["array1", "array2", "lambda"]],
  ["MAP_KEYS", ["map"]],
  ["MAP_VALUES", ["map"]],
  ["MAP_FROM_ENTRIES", ["entries"]],
  // 聚合
  ["APPROX_DISTINCT", ["x", "e"]],
  ["HISTOGRAM", ["x"]],
  ["MAX_BY", ["x", "y"]],
  ["MIN_BY", ["x", "y"]],
  ["STDDEV", ["x"]],
  ["VARIANCE", ["x"]],
  ["CORR", ["y", "x"]],
  // JSON / 转换
  ["JSON_EXTRACT", ["json", "path"]],
  ["JSON_EXTRACT_SCALAR", ["json", "path"]],
  ["JSON_FORMAT", ["json"]],
  ["JSON_PARSE", ["string"]],
  ["JSON_QUERY", ["json", "path"]],
  ["JSON_VALUE", ["json", "path"]],
  ["JSON_ARRAY_GET", ["json", "index"]],
  ["JSON_SIZE", ["json", "path"]],
  ["TRY", ["expression"]],
  ["TRY_CAST", ["expression AS type"]],
  ["IF", ["condition", "true_value", "false_value"]],
  ["COALESCE", ["...values"]],
  ["NULLIF", ["value1", "value2"]],
  ["GREATEST", ["...values"]],
  ["LEAST", ["...values"]],
]);

/** Trino/Presto 中参数语法特殊的函数，补全时按模板插入 */
export const TRINO_FUNCTION_APPLY_TEMPLATES = new Map<string, string>([
  ["EXTRACT", "EXTRACT(${field} FROM ${source})"],
  ["POSITION", "POSITION(${substring} IN ${string})"],
  ["SUBSTRING", "SUBSTRING(${string} FROM ${start} FOR ${length})"],
]);
